name: 'Current Branch Text Update Checker'
description: 'Updates GitHub links in text files (Markdown, reStructuredText, etc) to point to the current branch '
inputs:
  file-whitelist:
    description: 'JSON array of glob expressions corresponding to files/extensions that should be updated.'
    required: false
    default: '["**/*.md", "**/*.rst", "**/*.txt", "**/*.json", "**/*.yml", "**/*.xml"]'
  file-blacklist:
    description: 'JSON array of glob expressions corresponding to files/extensions that should not be updated. Overrides the whitelist.'
    required: false
    default: '["node_modules/**", ".github/**"]'
  target-branch:
    description: 'The name of the branch being merged in to.'
    required: true
  # github-token:
  #   description: 'The repository's GITHUB_TOKEN, used to authenticate with GitHub API queries'
  #   required: true
outputs:
  updated-files:
    description: 'JSON array of paths to files that were updated.'
runs:
  using: 'node16'
  main: 'index.js'