name: 'Current Branch Text Update Checker'
description: 'Updates GitHub links in text files (Markdown, reStructuredText, etc) to point to the current branch '
inputs:
  file-whitelist:
    description: 'JSON array of glob expressions corresponding to files/extensions that should be updated.'
    required: false
    default: '["*.md", "*.rst", "*.txt", "*.json", "*.yml", "*.xml"]'
  file-blacklist:
    description: 'JSON array of glob expressions corresponding to files/extensions that shouldn't be updated. Overrides the whitelist.'
    required: false
    default: '[]'
outputs:
  updated-files:
    description: 'JSON array of paths to files that were updated.'
runs:
  using: 'node18'
  main: 'index.js'